<?php

declare(strict_types=1);

namespace App\Services\Betting;

use App\Exceptions\BetPurchaseConcurrencyException;
use App\Models\Bet;
use App\Models\Ticket;
use Illuminate\Contracts\Config\Repository as ConfigRepository;
use Illuminate\Support\Str;

/**
 * Generates the human-facing references a purchase needs: bet_number, ticket_number
 * and the row UUIDs.
 *
 * WHY REFERENCES ARE NOT GENERATED INSIDE THE MODELS
 * App\Models\Ticket says it explicitly: "The ticket number is generated by the ticket
 * service, never inside this model." A model that generated its own reference would
 * do so on every save, would have no way to check uniqueness against soft-deleted
 * rows, and would make a reference appear during a rollback-bound transaction with no
 * one able to see where it came from. Reference generation is therefore a service
 * concern with one owner.
 *
 * WHY THE UNIQUE INDEX IS THE REAL GUARANTEE AND THIS CLASS IS ONLY AN OPTIMISATION
 * bets.bet_number and tickets.ticket_number both carry UNIQUE indexes in the Phase 1
 * schema. The pre-check below cannot be race-free - another transaction can insert
 * between the SELECT and the INSERT - and it does not pretend to be. Its job is to
 * make a collision vanishingly unlikely so the database rarely has to reject one; the
 * database remains the authority. When the pre-check keeps failing, the purchase is
 * abandoned with a concurrency exception rather than reusing an existing reference,
 * because two bets sharing one reference is worse than a refused purchase.
 *
 * WHY random_bytes AND NOT A COUNTER
 * A monotonic counter would need its own locked row, adding a third lock to every
 * purchase and a new deadlock surface, and it would leak business volume to anyone
 * holding a ticket. 12 hex characters from a cryptographically secure source give a
 * collision probability small enough that the retry loop below is effectively never
 * entered, without any coordination between processes.
 *
 * WHY SOFT-DELETED ROWS ARE INCLUDED IN THE CHECK
 * The unique indexes cover soft-deleted rows too, so a reference belonging to a
 * cancelled-and-soft-deleted bet is still taken. Checking without withTrashed() would
 * report "free" for a value the database will reject.
 *
 * NO FINANCIAL ARITHMETIC HAPPENS HERE
 * This class contains no amounts and no arithmetic of any kind.
 */
final class BetPurchaseReferenceService
{
    /**
     * How many times a colliding reference is regenerated before the purchase is
     * abandoned. Three is generous: with 48 bits of entropy per attempt, reaching the
     * third attempt indicates something other than chance.
     */
    public const MAX_ATTEMPTS = 3;

    /** Used when the project declares no bet reference prefix. */
    public const DEFAULT_BET_PREFIX = 'BT';

    /** Used when the project declares no ticket reference prefix. */
    public const DEFAULT_TICKET_PREFIX = 'TK';

    /** Hex characters of entropy in the random segment. */
    private const ENTROPY_HEX_LENGTH = 12;

    public function __construct(
        private readonly ConfigRepository $config,
    ) {
    }

    /**
     * A unique bets.bet_number.
     *
     * @throws BetPurchaseConcurrencyException when uniqueness cannot be reached
     */
    public function betNumber(): string
    {
        return $this->uniqueReference(
            $this->betPrefix(),
            'bet number',
            static fn (string $candidate): bool => Bet::withTrashed()
                ->where('bet_number', $candidate)
                ->exists(),
        );
    }

    /**
     * A unique tickets.ticket_number.
     *
     * @throws BetPurchaseConcurrencyException when uniqueness cannot be reached
     */
    public function ticketNumber(): string
    {
        return $this->uniqueReference(
            $this->ticketPrefix(),
            'ticket number',
            static fn (string $candidate): bool => Ticket::withTrashed()
                ->where('ticket_number', $candidate)
                ->exists(),
        );
    }

    /**
     * A UUID for the uuid column that bets and tickets both carry.
     *
     * The column is nullable, so this is not strictly required; it is populated
     * anyway because a stable external identifier that is not the auto-increment key
     * is what an API and a printed ticket should expose.
     */
    public function uuid(): string
    {
        return (string) Str::uuid();
    }

    /**
     * The configured bet reference prefix.
     *
     * config/lottery.php declares reference prefixes for draws ('DR'), tickets ('TK')
     * and payouts ('PO') but not for bets. Rather than adding a configuration key -
     * configuration files outside the requested file scope are not modified by this
     * phase - the optional key is read if a later phase adds it, and the documented
     * default is used until then.
     */
    public function betPrefix(): string
    {
        return $this->prefix('lottery.betting.reference_prefix', self::DEFAULT_BET_PREFIX);
    }

    /**
     * The configured ticket reference prefix, which the project declares as 'TK'.
     */
    public function ticketPrefix(): string
    {
        return $this->prefix('lottery.ticket.reference_prefix', self::DEFAULT_TICKET_PREFIX);
    }

    /**
     * The shape a reference takes, for reporting: PREFIX-YYYYMMDD-<12 hex>.
     *
     * Mirrors the shape App\Services\Finance\FinancialTransactionService already uses
     * for transaction references, so operators read one format everywhere.
     */
    public function referenceShape(string $prefix): string
    {
        return $prefix.'-YYYYMMDD-'.str_repeat('X', self::ENTROPY_HEX_LENGTH);
    }

    /**
     * @param  \Closure(string): bool  $taken
     *
     * @throws BetPurchaseConcurrencyException
     */
    private function uniqueReference(string $prefix, string $kind, \Closure $taken): string
    {
        for ($attempt = 1; $attempt <= self::MAX_ATTEMPTS; $attempt++) {
            $candidate = $this->candidate($prefix);

            if (! $taken($candidate)) {
                return $candidate;
            }
        }

        throw BetPurchaseConcurrencyException::referenceCollision($kind, self::MAX_ATTEMPTS);
    }

    private function candidate(string $prefix): string
    {
        return sprintf(
            '%s-%s-%s',
            $prefix,
            date('Ymd'),
            strtoupper(bin2hex(random_bytes(intdiv(self::ENTROPY_HEX_LENGTH, 2)))),
        );
    }

    private function prefix(string $configKey, string $default): string
    {
        $configured = $this->config->get($configKey);

        if (! is_string($configured)) {
            return $default;
        }

        $sanitised = preg_replace('/[^A-Za-z0-9]/', '', $configured) ?? '';

        return $sanitised === '' ? $default : strtoupper($sanitised);
    }
}
