@extends('layouts.app')

@php
    $tiers = is_array($grades['tiers'] ?? null) ? $grades['tiers'] : [];
    $status = (string) ($grades['status'] ?? trans('public_pages.not_configured'));
@endphp

@section('title', (string) ($meta['title'] ?? $grades['meta_title'] ?? trans('account_info.grades_meta_title')))
@section('meta_description', (string) ($meta['description'] ?? $grades['meta_description'] ?? trans('account_info.grades_meta_description')))
@section('meta_canonical', (string) ($meta['canonical'] ?? url('/account-grade')))
@section('meta_og_title', (string) ($meta['og_title'] ?? $grades['meta_title'] ?? trans('account_info.grades_meta_title')))
@section('meta_og_description', (string) ($meta['og_description'] ?? $grades['meta_description'] ?? trans('account_info.grades_meta_description')))
@section('meta_og_type', (string) ($meta['og_type'] ?? 'website'))
@section('meta_og_url', (string) ($meta['og_url'] ?? url('/account-grade')))

@push('styles')
    @vite('resources/css/pages/account-grades.css')
@endpush

@section('content')
<div class="next-public-page next-public-page--grade" data-next-public-page="grades">
    <a class="pp-skip-link" href="#grade-main">{{ trans('public_pages.skip_to_content') }}</a>
    <header class="next-page-header"><div class="next-shell next-page-header__inner"><a class="next-brand" href="{{ route('home') }}" aria-label="{{ trans('account_info.grade_home_aria') }}"><span class="next-brand__mark">TL</span><span>THAILOTTO<small>{{ trans('account_info.grade_brand_subtitle') }}</small></span></a><nav class="next-nav" aria-label="{{ trans('account_info.grade_primary_nav') }}"><a href="{{ route('home') }}">{{ trans('account_info.grade_nav_home') }}</a><a href="{{ route('about') }}">{{ trans('account_info.grade_nav_about') }}</a><a href="{{ route('account.verification') }}">{{ trans('account_info.grade_nav_verification') }}</a><a class="is-active" href="{{ route('account.grade') }}" aria-current="page">{{ trans('account_info.grade_nav_grades') }}</a><a href="{{ route('contact') }}">{{ trans('account_info.grade_nav_contact') }}</a></nav>@guest<a class="next-button next-button--gold" href="{{ route('login') }}">{{ trans('account_info.grade_login') }}</a>@else<a class="next-button next-button--gold" href="{{ route('account.grade') }}">{{ trans('account_info.grade_my_grade') }}</a>@endguest</div></header>
    <main id="grade-main" class="next-shell next-content" tabindex="-1">
        <section class="next-hero" aria-labelledby="grade-title"><div><p class="next-eyebrow">{{ trans('account_info.grade_eyebrow') }}</p><h1 id="grade-title">{{ trans('account_info.grades_title') }}</h1><p>{{ $grades['meta_description'] ?? 'Configured grade rules and published benefits.' }}</p><p class="next-note">{{ trans('account_info.grade_public_note') }}</p></div><div class="next-hero-object next-hero-object--grade" aria-hidden="true"><span>◆</span></div></section>
        <section class="next-meta-strip" aria-label="{{ trans('account_info.grade_metadata_aria') }}"><div><span>{{ trans('account_info.grade_rule_version') }}</span><strong>{{ $grades['rule_version'] ?? trans('public_pages.not_configured') }}</strong></div><div><span>{{ trans('account_info.grade_review_period') }}</span><strong>{{ ($grades['period_days'] ?? 0) > 0 ? trans('account_info.grade_days', ['days' => $grades['period_days']]) : trans('public_pages.not_configured') }}</strong></div><div><span>{{ trans('account_info.grade_currency') }}</span><strong>{{ $grades['currency'] ?? trans('public_pages.not_configured') }}</strong></div><div><span>{{ trans('account_info.grade_public_tiers') }}</span><strong>{{ count($tiers) }}</strong></div></section>
        <section class="next-panel" aria-labelledby="grade-summary-title"><p class="next-eyebrow">{{ trans('account_info.grade_ladder_summary') }}</p><h2 id="grade-summary-title">{{ trans('account_info.ladder_heading') }}</h2><div class="next-table-wrap"><table class="next-table"><caption class="sr-only">{{ trans('account_info.ladder_caption') }}</caption><thead><tr><th scope="col">{{ trans('account_info.col_sl') }}</th><th scope="col">{{ trans('account_info.col_grade') }}</th><th scope="col">{{ trans('account_info.col_min_spend') }}</th><th scope="col">{{ trans('account_info.col_discount') }}</th><th scope="col">{{ trans('account_info.col_discount_of_game') }}</th></tr></thead><tbody>@foreach ($tiers as $tier)<tr data-grade-tier="{{ $tier['key'] ?? $loop->iteration }}"><th scope="row">{{ $tier['sl'] ?? trans('public_pages.not_configured') }}</th><td>{{ $tier['name'] ?? trans('public_pages.not_configured') }}</td><td>{{ $tier['min_spend'] ?? trans('public_pages.not_configured') }}</td><td>{{ $tier['discount_display'] ?? trans('public_pages.not_configured') }}</td><td>{{ $tier['eligible_game_count'] ?? trans('public_pages.not_configured') }}</td></tr>@endforeach</tbody></table></div></section>
        <div class="next-layout"><aside class="next-sidebar" aria-label="{{ trans('account_info.grade_ladder_map') }}"><p class="next-eyebrow">{{ trans('account_info.grade_ladder_map') }}</p>@foreach ($tiers as $tier)<a href="#grade-{{ $tier['key'] ?? $loop->iteration }}" data-content-link="grade-{{ $tier['key'] ?? $loop->iteration }}">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }} · {{ $tier['name'] ?? trans('account_info.grade_tier_fallback') }}</a>@endforeach<a href="#grade-private" data-content-link="grade-private">{{ trans('account_info.grade_private_account') }}</a></aside><div>
            @forelse ($tiers as $tier)
                @php $tierId = 'grade-'.($tier['key'] ?? $loop->iteration); @endphp
                <section class="next-section" id="{{ $tierId }}" data-content-section data-grade-tier="{{ $tier['key'] ?? $loop->iteration }}" data-search-item data-search-text="{{ ($tier['name'] ?? '').' '.($tier['discount_display'] ?? '').' '.($tier['scope'] ?? '') }}" aria-labelledby="{{ $tierId }}-title"><div class="next-section__heading"><span class="next-section__number">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div><p class="next-eyebrow">{{ trans('account_info.grade_configured_tier') }}</p><h2 id="{{ $tierId }}-title">{{ $tier['name'] ?? trans('account_info.grade_tier_fallback') }}</h2></div></div><div class="next-card-grid"><div class="next-card"><h3>{{ trans('account_info.grade_minimum_spend') }}</h3><p>{{ $tier['min_spend'] ?? trans('public_pages.not_configured') }} {{ $grades['currency'] ?? '' }}</p></div><div class="next-card"><h3>{{ trans('account_info.grade_published_discount') }}</h3><p>{{ $tier['discount_display'] ?? trans('public_pages.not_configured') }}</p></div><div class="next-card"><h3>{{ trans('account_info.grade_scope') }}</h3><p>{{ $tier['scope'] ?? trans('public_pages.not_configured') }}</p></div></div><div class="next-section__body"><p>{{ trans('account_info.grade_eligible_games', ['count' => $tier['eligible_game_count'] ?? 0]) }}</p>@if (!empty($tier['eligible_games']))<ul>@foreach ($tier['eligible_games'] as $game)<li>{{ $game['label'] ?? $game['key'] ?? trans('public_pages.not_configured') }}</li>@endforeach</ul>@endif</div></section>
            @empty
                <section class="next-panel" role="status"><h2>{{ trans('account_info.grade_unavailable_title') }}</h2><p>{{ trans('account_info.grade_unavailable_body') }}</p></section>
            @endforelse
            @php $matrix = is_array($matrix ?? null) ? $matrix : []; $matrixLotteries = is_array($matrix['lotteries'] ?? null) ? $matrix['lotteries'] : []; @endphp
            <section class="next-section" id="grade-game-matrix" data-content-section aria-labelledby="grade-game-matrix-title"><div class="next-section__heading"><span class="next-section__number">Σ</span><div><p class="next-eyebrow">{{ trans('account_info.col_discount_of_game') }}</p><h2 id="grade-game-matrix-title">{{ trans('account_info.col_discount_of_game') }}</h2></div></div><p class="next-section__body">{{ trans('account_info.discount_scope_note') }}</p>@foreach ($tiers as $tier)<button class="next-button" type="button" data-grade-games-toggle aria-expanded="false" aria-controls="grade-games-{{ $tier['key'] ?? $loop->iteration }}">{{ $tier['name'] ?? trans('account_info.grade_tier_fallback') }}</button><div id="grade-games-{{ $tier['key'] ?? $loop->iteration }}" data-grade-game-count="{{ $tier['eligible_game_count'] ?? 0 }}" hidden><p class="next-muted">{{ trans('account_info.col_sl') }} {{ $tier['sl'] ?? trans('public_pages.not_configured') }} · {{ trans('account_info.col_discount') }} {{ $tier['discount_display'] ?? trans('public_pages.not_configured') }}</p><ul>@foreach ((array) ($tier['eligible_games'] ?? []) as $game)<li>{{ $game['label'] ?? $game['key'] ?? trans('public_pages.not_configured') }}</li>@endforeach</ul></div>@endforeach@if ($matrixLotteries !== [])<div class="next-table-wrap"><table class="next-table"><thead><tr><th>{{ trans('account_info.col_grade') }}</th><th>{{ trans('account_info.col_discount') }}</th><th>{{ trans('account_info.col_discount_of_game') }}</th></tr></thead><tbody>@foreach ($matrixLotteries as $lottery)<tr data-grade-games-lottery="{{ $lottery['key'] ?? '' }}"><td>{{ $lottery['label'] ?? trans('public_pages.not_configured') }}</td><td>{{ $lottery['affiliate_commission_percent'] ?? trans('public_pages.not_configured') }}</td><td>{{ count((array) ($lottery['games'] ?? [])) }}</td></tr>@endforeach</tbody></table></div>@else<p class="next-empty">{{ trans('public_pages.not_configured') }}</p>@endif</section>
            <section class="next-section" id="grade-private" data-content-section aria-labelledby="grade-private-title"><div class="next-section__heading"><span class="next-section__number">{{ trans('account_info.grade_private_marker') }}</span><div><p class="next-eyebrow">{{ trans('account_info.grade_private_eyebrow') }}</p><h2 id="grade-private-title">{{ trans('account_info.grade_private_title') }}</h2></div></div><div class="next-section__body"><p>{{ trans('account_info.grade_private_body') }}</p><p class="next-muted">{{ trans('account_info.grade_private_note') }}</p></div></section>
        </div></div>
        <section class="next-bottom"><div><p class="next-eyebrow">{{ trans('account_info.grade_check_account') }}</p><h2>{{ trans('account_info.grade_open_authenticated') }}</h2><p>{{ trans('account_info.grade_authenticated_body') }}</p></div><div class="next-bottom__links">@guest<a class="next-button next-button--gold" href="{{ route('login') }}">{{ trans('account_info.grade_sign_in') }}</a>@else<a class="next-button next-button--gold" href="{{ route('account.grade') }}">{{ trans('account_info.grade_open_my_grade') }}</a>@endguest<a class="next-button" href="{{ route('contact') }}">{{ trans('account_info.grade_contact_support') }}</a></div></section>
    </main>
</div>
@endsection

@push('scripts')
    @vite('resources/js/pages/account-grades.js')
@endpush
