import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/lottery.css',
                'resources/css/home.css',
        'resources/css/public-pages.css',
        'resources/css/pages/about.css',
        'resources/css/pages/vision.css',
        'resources/css/pages/terms.css',
        'resources/css/account-services.css',
                'resources/css/prize-discount.css',
                // PROMPT 5: National Lottery result surface.
                'resources/css/national-lottery.css',
                // PROMPT 6: Weekly Lottery result surface.
                'resources/css/weekly-lottery.css',
                'resources/css/bingo-lottery.css',
                'resources/css/pcso-lottery.css',
                'resources/css/contact.css',
                'resources/css/pages/public-next-pages.css',
                'resources/css/pages/privacy.css',
                'resources/css/pages/fees.css',
                'resources/css/pages/account-verification.css',
                'resources/css/pages/account-grades.css',
                'resources/css/pages/prize-verification.css',
                'resources/css/pages/discounts.css',
                'resources/css/pages/how-to-play.css',
                'resources/css/pages/faq.css',
                'resources/css/pages/contact.css',
                'resources/css/pages/download.css',
                'resources/css/auth-portal.css',
                'resources/css/admin-lottofin.css',
                'resources/css/glo-results-checker.css',
                'resources/css/glo-l6.css',
                'resources/css/player-security-settings.css',
                'resources/css/thai-lottery-betting.css',
                'resources/css/player-dashboard.css',
                'resources/css/wallet-management.css',
                'resources/css/deposit-portal.css',
                'resources/css/withdrawal-portal.css',
                'resources/css/player-profile.css',
                'resources/css/lottery-history.css',
                'resources/css/player-settings.css',
        'resources/js/app.js',
        'resources/js/public-pages.js',
        'resources/js/pages/about.js',
        'resources/js/pages/vision.js',
        'resources/js/pages/terms.js',
        'resources/js/auth-portal.js',
        'resources/js/admin-lottofin.js',
        'resources/js/glo-results-checker.js',
        'resources/js/player-security-settings.js',
        'resources/js/thai-lottery-betting.js',
        'resources/js/player-dashboard.js',
        'resources/js/wallet-management.js',
        'resources/js/deposit-portal.js',
        'resources/js/withdrawal-portal.js',
        'resources/js/player-profile.js',
        'resources/js/lottery-history.js',
        'resources/js/player-settings.js',
        'resources/js/privacy-portal.js',
        'resources/js/fees-portal.js',
        'resources/js/account-verification-portal.js',
        'resources/js/account-grade-portal.js',
        'resources/js/prize-verification-portal.js',
        'resources/js/lotto-discount-portal.js',
        'resources/js/how-to-play-portal.js',
        'resources/js/faq-portal.js',
        'resources/js/contact-portal.js',
        'resources/js/download-app-portal.js',
        'resources/js/components/AuthCard.tsx',
        'resources/js/components/LottoFinAdminDashboard.tsx',
        'resources/js/components/GloResultsChecker.tsx',
        'resources/js/components/PlayerSecuritySettings.tsx',
        'resources/js/components/ThaiLotteryBetting.tsx',
        'resources/js/components/PlayerDashboard.tsx',
        'resources/js/components/WalletManagement.tsx',
        'resources/js/components/DepositPortal.tsx',
        'resources/js/components/WithdrawalPortal.tsx',
        'resources/js/components/PlayerProfile.tsx',
        'resources/js/components/LotteryHistory.tsx',
        'resources/js/components/PlayerSettings.tsx',
        'resources/js/account-verification.js',
        'resources/js/account-grade.js',
                'resources/js/prize-verification.js',
                'resources/js/national-lottery.js',
                'resources/js/weekly-lottery.js',
                'resources/js/bingo-lottery.js',
                'resources/js/pcso-lottery.js',
                'resources/js/contact.js',
                'resources/js/pages/public-next-pages.js',
                'resources/js/pages/privacy.js',
                'resources/js/pages/fees.js',
                'resources/js/pages/account-verification.js',
                'resources/js/pages/account-grades.js',
                'resources/js/pages/prize-verification.js',
                'resources/js/pages/discounts.js',
                'resources/js/pages/how-to-play.js',
                'resources/js/pages/faq.js',
                'resources/js/pages/contact.js',
                'resources/js/pages/download.js',
                'resources/js/lottery/ticket-selector.js',
                'resources/js/lottery/countdown.js',
                'resources/js/lottery/bet-slip.js',
                'resources/js/lottery/live-results.js',
                'resources/js/wallet/wallet-balance.js',
                'resources/js/home/countdown.js',
                'resources/js/home/live-draw.js',
            ],
            refresh: true,
        }),
    ],
    server: {
        host: '0.0.0.0',
        port: 5173,
    },
});
