<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\ContactMessage;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * Synthetic contact messages (PROMPT 10).
 *
 * EVERY ADDRESS IS @example.test, the domain reserved for exactly this. A
 * factory that generated plausible real addresses would eventually have one
 * emailed by a misconfigured environment.
 *
 * No fingerprint is generated by default. They are keyed hashes computed from
 * a real request, and inventing one would put a value in the column that
 * matches nothing - which is worse than null for a column whose only job is
 * matching.
 *
 * @extends Factory<ContactMessage>
 */
class ContactMessageFactory extends Factory
{
    protected $model = ContactMessage::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->name(),
            'email' => fake()->userName().'@example.test',
            'subject' => 'Synthetic support question',
            'message' => 'This is synthetic development data, not a real enquiry.',
            'status' => ContactMessage::STATUS_RECEIVED,
            // The honest default for a fresh clone: stored, nothing forwarded.
            'delivery_state' => ContactMessage::DELIVERY_NOT_CONFIGURED,
            'locale' => 'en',
        ];
    }

    /** A message an operator has finished with, and which retention may purge. */
    public function resolved(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => ContactMessage::STATUS_RESOLVED,
            'resolved_at' => now(),
        ]);
    }

    /** A message the honeypot caught. */
    public function spam(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => ContactMessage::STATUS_SPAM,
            'delivery_state' => ContactMessage::DELIVERY_NOT_ATTEMPTED,
        ]);
    }
}
