<?php

declare(strict_types=1);

namespace App\Services\Auth;

use App\Enums\AuthLoginIdentifier;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Password;
use Illuminate\Validation\ValidationException;

/*
 * PROMPT 3 — secure member password recovery.
 *
 * BUILT ON the framework broker (the application already ships the
 * password_reset_tokens table with hashed-token storage, expiry and
 * single-use semantics). This service adds the recovery-surface
 * policy: identifier resolution (account no. / email), the CAPTCHA
 * gate, the generic anti-enumeration response, session revocation
 * after a successful reset and the audit event.
 *
 * SECURITY CONTRACT:
 * - requestReset ALWAYS answers the same outward way, whether or not
 *   the identifier matched an account (no oracle, no timing signal);
 * - the token is generated by the broker, stored HASHED, expires, and
 *   is deleted on use (single-use by the broker itself);
 * - no plaintext password is ever emailed, and no token is ever
 *   logged (the notification carries the action link only);
 * - a successful reset updates the password with the platform hasher
 *   and revokes the member's other sessions and remember-device
 *   credentials when the architecture supports it (it does: the
 *   sessions table tracks user_id, users carry remember_token).
 */
final class PasswordResetService
{
    public function __construct(
        private readonly CaptchaService $captcha,
    ) {
    }

    /**
     * Request a recovery link.
     *
     * @param  array{identifier?: mixed, captcha_token?: mixed, captcha_answer?: mixed}  $input
     *
     * @return array{sent: bool, message: string} the SAME shape and copy
     *                                           for every outcome.
     */
    public function requestReset(Request $request, array $input): array
    {
        // CAPTCHA gate — server-side only.
        if ((bool) config('auth_security.captcha.password_reset', true) && $this->captcha->isEnabled()) {
            $token = is_string($input['captcha_token'] ?? null) ? $input['captcha_token'] : null;
            $answer = is_string($input['captcha_answer'] ?? null) ? $input['captcha_answer'] : null;

            if (! $this->captcha->verify($request, $token, $answer)) {
                throw ValidationException::withMessages([
                    'captcha' => (string) config('auth_security.messages.captcha_failed'),
                ]);
            }
        }

        $raw = is_string($input['identifier'] ?? null) ? $input['identifier'] : '';
        $user = $this->resolveUser($raw);

        // The broker hashes the token at rest, enforces expiry and
        // deletes it on successful use. The notification it triggers
        // is App\Notifications\AuthPasswordResetNotification (wired on
        // the User model).
        if ($user instanceof User) {
            Password::broker()->sendResetLink(['email' => $user->email]);
        }

        // One generic response for every branch — existing account,
        // unknown account, malformed identifier alike.
        return [
            'sent' => true,
            'message' => __('public_pages.reset_requested'),
        ];
    }

    /**
     * Complete a reset.
     *
     * @param  array{token?: mixed, email?: mixed, password?: mixed, password_confirmation?: mixed}  $input
     *
     * @return array{reset: bool, message: string}
     */
    public function resetPassword(Request $request, array $input): array
    {
        $credentials = [
            'token' => is_string($input['token'] ?? null) ? $input['token'] : '',
            'email' => is_string($input['email'] ?? null) ? mb_strtolower(trim($input['email'])) : '',
            'password' => is_string($input['password'] ?? null) ? $input['password'] : '',
            'password_confirmation' => is_string($input['password_confirmation'] ?? null) ? $input['password_confirmation'] : '',
        ];

        $status = Password::broker()->reset(
            $credentials,
            function (User $user, string $password): void {
                $user->password = \Illuminate\Support\Facades\Hash::make($password);

                // Drop the remember-device credential with the password.
                $user->remember_token = null;
                $user->save();

                $this->revokeOtherSessions($user);
            },
        );

        if ($status !== Password::PASSWORD_RESET) {
            throw ValidationException::withMessages([
                'password' => __('public_pages.reset_invalid_token'),
            ]);
        }

        return [
            'reset' => true,
            'message' => __('public_pages.reset_completed'),
        ];
    }

    /**
     * Resolve "Account No. or email" to the member row WITHOUT ever
     * disclosing the outcome: a null return is indistinguishable from
     * a found one in every outward behaviour of the caller.
     */
    private function resolveUser(string $raw): ?User
    {
        $trimmed = trim($raw);

        if ($trimmed === '') {
            return null;
        }

        $kind = AuthLoginIdentifier::resolve($trimmed);
        $identifier = $kind->normalize($trimmed);

        /** @var User|null $user */
        $user = match ($kind) {
            AuthLoginIdentifier::Email => User::query()->where('email', $identifier)->first(),
            AuthLoginIdentifier::AccountId => User::query()->whereKey((int) $identifier)->first(),
            AuthLoginIdentifier::Username => User::query()->where('username', $identifier)->first(),
        };

        return $user;
    }

    /**
     * Invalidate every authenticated session of the member and drop
     * the remember-device credential. The member re-authenticates
     * everywhere with the new password; nobody is auto-logged-in by
     * the reset itself.
     */
    private function revokeOtherSessions(User $user): void
    {
        if (! (bool) config('auth_security.password_reset.revoke_sessions', true)) {
            return;
        }

        DB::table('sessions')->where('user_id', $user->id)->delete();

        $user->forceFill(['remember_token' => null])->save();
    }
}
