<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\Currency;
use App\Enums\TicketStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;

/**
 * A finalized betting ticket: the receipt that groups the bets a user submitted
 * together for one draw.
 *
 * One ticket has many bets, so the relationship is tickets 1-N bets; the
 * counters and the total amount are cached sums maintained by the betting
 * service when the ticket is confirmed.
 *
 * The ticket number is generated by the ticket service, never inside this model.
 *
 * @property int $id
 * @property string $ticket_number
 * @property int $user_id
 * @property int $draw_id
 * @property TicketStatus $status
 * @property Currency $currency
 * @property string $total_amount
 * @property int $total_bets
 * @property int $total_numbers
 * @property Carbon|null $issued_at
 * @property Carbon|null $confirmed_at
 * @property Carbon|null $cancelled_at
 * @property Carbon|null $expired_at
 * @property array<string, mixed>|null $metadata
 */
class Ticket extends Model
{
    /** @use HasFactory<Factory> */
    use HasFactory;

    use SoftDeletes;

    /**
     * Issue-time fields only.
     *
     * status and the lifecycle timestamps are advanced by the ticket service;
     * total_amount and the counters are derived from the bets that belong to the
     * ticket, so neither is accepted from request input.
     *
     * @var list<string>
     */
    protected $fillable = [
        'ticket_number',
        'user_id',
        'draw_id',
        'currency',
        'metadata',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'status' => TicketStatus::class,
            'currency' => Currency::class,
            'total_amount' => 'decimal:2',
            'total_bets' => 'integer',
            'total_numbers' => 'integer',
            'issued_at' => 'datetime',
            'confirmed_at' => 'datetime',
            'cancelled_at' => 'datetime',
            'expired_at' => 'datetime',
            'metadata' => 'array',
        ];
    }

    /**
     * @return BelongsTo<User, self>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo<Draw, self>
     */
    public function draw(): BelongsTo
    {
        return $this->belongsTo(Draw::class);
    }

    /**
     * @return HasMany<Bet>
     */
    public function bets(): HasMany
    {
        return $this->hasMany(Bet::class);
    }

    /**
     * Every selected number on the ticket, reached through its bets.
     *
     * @return HasManyThrough<BetItem>
     */
    public function betItems(): HasManyThrough
    {
        return $this->hasManyThrough(BetItem::class, Bet::class, 'ticket_id', 'bet_id');
    }

    /**
     * Payouts settled against this ticket.
     *
     * The payouts table carries a nullable ticket_id foreign key, so the
     * relationship is a plain one-to-many on that column.
     *
     * @return HasMany<Payout>
     */
    public function payouts(): HasMany
    {
        return $this->hasMany(Payout::class);
    }

    public function isValid(): bool
    {
        return $this->status->isValid();
    }

    public function isConfirmed(): bool
    {
        return $this->status === TicketStatus::Confirmed;
    }

    public function canCancel(): bool
    {
        return $this->status->canCancel();
    }

    public function isFinal(): bool
    {
        return $this->status->isFinal();
    }

    /**
     * @param  Builder<self>  $query
     * @return Builder<self>
     */
    public function scopeConfirmed(Builder $query): Builder
    {
        return $query->where('status', TicketStatus::Confirmed);
    }

    /**
     * @param  Builder<self>  $query
     * @return Builder<self>
     */
    public function scopePending(Builder $query): Builder
    {
        return $query->where('status', TicketStatus::Pending);
    }

    /**
     * @param  Builder<self>  $query
     * @return Builder<self>
     */
    public function scopeForUser(Builder $query, int $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    /**
     * @param  Builder<self>  $query
     * @return Builder<self>
     */
    public function scopeForDraw(Builder $query, int $drawId): Builder
    {
        return $query->where('draw_id', $drawId);
    }

    /**
     * @param  Builder<self>  $query
     * @return Builder<self>
     */
    public function scopeByTicketNumber(Builder $query, string $ticketNumber): Builder
    {
        return $query->where('ticket_number', $ticketNumber);
    }
}
