<?php

declare(strict_types=1);

namespace App\Services\Draw;

use App\DTOs\DrawResultData;
use App\DTOs\MarketRuleData;
use App\Enums\DrawLifecycleState;
use App\Exceptions\DrawLifecycleException;
use App\Models\Draw;
use App\Models\DrawResult;
use App\Models\WinningNumber;
use App\Services\Betting\MarketPayoutService;
use App\Services\Betting\MarketRuleResolver;
use Illuminate\Contracts\Config\Repository as ConfigRepository;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;

/**
 * Publishes ONE official result for ONE draw, atomically, exactly once.
 *
 * WHAT A PUBLICATION DOES, ALL OR NOTHING
 *   1. locks the draw row with SELECT ... FOR UPDATE
 *   2. refuses unless the lifecycle state is ResultPending
 *   3. refuses when a draw_results row already exists
 *   4. validates the submitted numbers through DrawResultValidator
 *   5. writes the draw_results row, with the bottom two in its metadata JSON
 *   6. writes one winning_numbers row per configured market
 *   7. moves the draw ResultPending -> ResultPublished
 *
 * All seven happen inside one database transaction. A failure at any step leaves NO
 * draw_results row, NO winning_numbers rows and the draw still in ResultPending,
 * which is the "no partial result publication" requirement.
 *
 * DUPLICATE PUBLICATION IS REFUSED THREE TIMES OVER
 *   application  DrawLifecycleService::assertCanPublishResult() refuses unless the
 *                state is ResultPending, so a ResultPublished or Settled draw is
 *                refused before any write
 *   existence    an explicit locked check for an existing draw_results row, so a row
 *                that exists without the matching state is still refused
 *   database     draw_results has unique('draw_id') and winning_numbers has unique
 *                (draw_id, bet_type, number, prize_tier); a race that somehow passed
 *                both checks is refused by the engine and translated below
 * None of these is a cache entry.
 *
 * THE SCHEMA IS USED AS IT IS
 *   first_prize   ->  draw_results.first_prize, varchar(16), model cast 'string'
 *   bottom two    ->  draw_results.metadata JSON, key
 *                     config('lottery.results.bottom_two_metadata_key'), because
 *                     THERE IS NO bottom_two COLUMN and Phase 5.1 creates none
 *   winning values->  winning_numbers rows, the table that already exists for them
 * No winning_numbers JSON column is added to draws, no bottom_two column is
 * invented, and Phase 5.1 ships NO migration.
 *
 * WINNING NUMBERS COME FROM CONFIGURATION, NOT FROM A HARD CODED LIST
 * The rows are generated by walking MarketRuleResolver::all(), so which markets
 * exist, which drawn value decides each and which multiplier applies all stay in
 * config('lottery.markets'). run_top's row carries the THREE digit top value,
 * because that is the value the verified RunMatchService tests its single digit
 * against; run_bottom's carries the two digit bottom for the same reason.
 *
 * NO CALLER CONTROLLED WINNERS OR MONEY
 * The caller supplies drawn numbers only. Winning values are derived by substr(),
 * multipliers are read from configuration through MarketPayoutService, and
 * DrawResultValidator refuses any attempt to submit a winner flag, a multiplier, a
 * payout or a force/override/bypass field. total_winners, total_payout and
 * house_profit are left at their column defaults: they are settlement summaries, and
 * Phase 5.1 does not pretend to fill them from a publication.
 *
 * NON-MONETARY
 * No wallet is read or written, no ledger entry is created, no financial transaction
 * is created, no payouts row is created and no payment gateway is called.
 *
 * NO RAW SQL
 * Every read and write goes through Eloquent. There is no DB::statement, DB::raw,
 * DB::select, DB::update or DB::unprepared call in this class.
 */
class DrawResultPublicationService
{
    public function __construct(
        private readonly ConfigRepository $config,
        private readonly DrawLifecycleService $lifecycle,
        private readonly DrawResultValidator $validator,
        private readonly MarketRuleResolver $rules,
        private readonly MarketPayoutService $payouts,
    ) {}

    /**
     * Publish the official result of a draw.
     *
     * @param  array<string, mixed>  $input  the submitted result; first_prize and
     *                                       bottom_two are required and must be
     *                                       digit strings
     * @return array{draw: Draw, result: DrawResult, winning_numbers: list<WinningNumber>, data: DrawResultData}
     *
     * @throws DrawLifecycleException
     * @throws \App\Exceptions\DrawResultValidationException
     */
    public function publish(int $drawId, array $input): array
    {
        // Validated BEFORE the transaction opens, so a malformed submission never
        // takes a row lock and never holds one while it is rejected. Validation
        // reads nothing from the database.
        $data = $this->validator->validate($input);

        $run = function () use ($drawId, $data): array {
            $draw = $this->lifecycle->lockForUpdate($drawId);

            $this->lifecycle->assertCanPublishResult($draw, [
                'stage' => 'publication',
            ]);

            $this->assertNoExistingResult($drawId);

            $result = $this->writeResult($draw, $data);
            $winningNumbers = $this->writeWinningNumbers($draw, $data);

            $draw = $this->lifecycle->markResultPublished($draw, [
                'stage' => 'publication',
                'first_prize' => $data->firstPrize(),
            ]);

            return [
                'draw' => $draw,
                'result' => $result,
                'winning_numbers' => $winningNumbers,
                'data' => $data,
            ];
        };

        try {
            if (DB::transactionLevel() > 0) {
                // Joining an outer transaction is allowed so a caller can compose
                // publication with other work and still get one rollback boundary.
                return $run();
            }

            return DB::transaction($run);
        } catch (QueryException $exception) {
            // The database's own duplicate guard is translated into the domain
            // refusal, so a race reports "already published" rather than leaking an
            // SQL error. The original is kept as $previous for the log; its message
            // is not surfaced.
            if ($this->isUniqueViolation($exception)) {
                throw DrawLifecycleException::duplicatePublication(
                    $drawId,
                    'database unique constraint on draw_results.draw_id or winning_numbers '
                    .'(draw_id, bet_type, number, prize_tier)',
                    ['stage' => 'publication'],
                    $exception,
                );
            }

            throw $exception;
        }
    }

    /**
     * Whether a draw already has a published official result.
     */
    public function hasPublishedResult(int $drawId): bool
    {
        return DrawResult::query()->where('draw_id', $drawId)->exists();
    }

    /**
     * The published result of a draw, or null.
     */
    public function resultFor(int $drawId): ?DrawResult
    {
        return DrawResult::query()->where('draw_id', $drawId)->first();
    }

    /**
     * The published winning numbers of a draw, oldest row first.
     *
     * @return list<WinningNumber>
     */
    public function winningNumbersFor(int $drawId): array
    {
        return WinningNumber::query()
            ->where('draw_id', $drawId)
            ->orderBy('id')
            ->get()
            ->all();
    }

    /**
     * The rows a publication WOULD write, without writing anything.
     *
     * Used by the publication test to prove the generated values before any row
     * exists, and by reports.
     *
     * @return list<array<string, mixed>>
     */
    public function previewWinningNumbers(DrawResultData $data): array
    {
        $rows = [];

        foreach ($this->publishableRules() as $marketKey => $rule) {
            $multiplier = $this->payouts->multiplierFor($marketKey);

            $rows[] = [
                'market' => $marketKey,
                'bet_type' => $rule->betType->value,
                'number' => $data->valueFor($rule->resultType()),
                'prize_tier' => $rule->resultType()->value,
                'position' => $rule->side->value,
                'payout_multiplier' => $multiplier->toBetItemColumn(),
                'multiplier_exact' => $multiplier->value(),
            ];
        }

        return $rows;
    }

    /**
     * The publication rules in report form.
     *
     * @return array<string, mixed>
     */
    public function audit(): array
    {
        return [
            'result_columns_written' => ['draw_id', 'first_prize', 'published_at', 'metadata'],
            'result_columns_not_written' => [
                'total_winners' => 'settlement summary, left at the column default',
                'total_payout' => 'settlement summary, left at the column default',
                'house_profit' => 'settlement summary, left at the column default',
            ],
            'bottom_two_storage' => sprintf(
                'draw_results.metadata JSON key "%s"; there is no bottom_two column and none was created',
                $this->bottomTwoMetadataKey(),
            ),
            'winning_numbers_source' => 'config(lottery.markets) via MarketRuleResolver::all()',
            'duplicate_guards' => [
                'lifecycle' => 'state must be '.DrawLifecycleState::ResultPending->value,
                'existence' => 'no draw_results row may exist for the draw',
                'database' => 'unique(draw_results.draw_id) and unique(winning_numbers.draw_id, '
                    .'bet_type, number, prize_tier)',
            ],
            'migrations_added' => 0,
            'guarantees' => $this->guarantees(),
        ];
    }

    /**
     * @return array<string, string>
     */
    public function guarantees(): array
    {
        return [
            'atomic' => 'The result row, the winning number rows and the state change are one '
                .'transaction. A failure leaves no partial publication.',
            'exactly_once' => 'Refused by the lifecycle state, by an existence check under the draw '
                .'lock, and by database unique keys. No cache is involved.',
            'no_new_columns' => 'The existing draw_results and winning_numbers schema is used as it '
                .'is. No bottom_two column and no draws.winning_numbers JSON column was created, and '
                .'Phase 5.1 adds no migration.',
            'strings_only' => 'Winning values are substr() reads of the validated first prize, or the '
                .'validated bottom two. No intval(), floatval(), round() or float cast appears here.',
            'server_derived' => 'The caller supplies drawn numbers only. Winning values are derived '
                .'and multipliers come from configuration; no winner flag, multiplier or prize amount '
                .'is accepted as input.',
            'configured_multipliers' => 'Rates come from MarketPayoutService, which reads '
                .'config(lottery.markets.<key>.payout_multiplier). The legacy per bet type Run '
                .'multiplier is never used.',
            'no_money' => 'No wallet, ledger entry, financial transaction, payouts row, deposit, '
                .'withdrawal or payment gateway is touched.',
            'no_raw_sql' => 'Every statement goes through Eloquent; there is no DB::statement, DB::raw, '
                .'DB::select, DB::update or DB::unprepared call.',
            'no_leakage' => 'A database unique violation is translated into a domain refusal; the SQL '
                .'message is kept only as the previous exception and is not surfaced.',
        ];
    }

    /**
     * Refuse when a result row already exists for the draw.
     *
     * Read INSIDE the draw lock, so it cannot race a concurrent publication: the
     * second caller blocks on the draw row until the first commits, then sees the row.
     *
     * @throws DrawLifecycleException
     */
    private function assertNoExistingResult(int $drawId): void
    {
        if (DrawResult::query()->where('draw_id', $drawId)->exists()) {
            throw DrawLifecycleException::duplicatePublication(
                $drawId,
                'an existing draw_results row for the draw',
                ['stage' => 'publication'],
            );
        }

        if (WinningNumber::query()->where('draw_id', $drawId)->exists()) {
            throw DrawLifecycleException::duplicatePublication(
                $drawId,
                'existing winning_numbers rows for the draw',
                ['stage' => 'publication'],
            );
        }
    }

    /**
     * Write the draw_results row.
     */
    private function writeResult(Draw $draw, DrawResultData $data): DrawResult
    {
        $result = new DrawResult();

        $result->fill($data->toResultColumns() + [
            'draw_id' => $draw->getKey(),
            // published_at is set because the verified MarketResultResolver refuses
            // to read an unpublished result while
            // config('lottery.payouts.require_published_result') is true, which it is.
            'published_at' => now(),
            'metadata' => $data->metadataPayload($this->bottomTwoMetadataKey()),
        ]);

        $result->save();

        return $result;
    }

    /**
     * Write one winning_numbers row per publishable market.
     *
     * @return list<WinningNumber>
     *
     * @throws DrawLifecycleException
     */
    private function writeWinningNumbers(Draw $draw, DrawResultData $data): array
    {
        $rows = [];
        $seen = [];

        foreach ($this->publishableRules() as $marketKey => $rule) {
            $number = $data->valueFor($rule->resultType());
            $tier = $rule->resultType()->value;

            // The unique key is (draw_id, bet_type, number, prize_tier) and does NOT
            // include position, so two markets sharing a bet type, a winning value
            // and a result tier would collide. With the six configured markets that
            // cannot happen. It is checked rather than assumed, and reported rather
            // than silently skipped, because skipping would publish an incomplete
            // set of official numbers.
            $fingerprint = $rule->betType->value.'|'.$number.'|'.$tier;

            if (isset($seen[$fingerprint])) {
                throw DrawLifecycleException::duplicatePublication(
                    (int) $draw->getKey(),
                    sprintf(
                        'two configured markets ("%s" and "%s") produce the same winning_numbers key '
                        .'(bet_type %s, number %s, prize_tier %s), which the unique index forbids',
                        $seen[$fingerprint],
                        $marketKey,
                        $rule->betType->value,
                        $number,
                        $tier,
                    ),
                    ['stage' => 'publication', 'market' => $marketKey],
                );
            }

            $seen[$fingerprint] = $marketKey;

            $multiplier = $this->payouts->multiplierFor($marketKey);

            $row = new WinningNumber();

            $row->fill([
                'draw_id' => $draw->getKey(),
                'bet_type' => $rule->betType,
                'number' => $number,
                'prize_tier' => $tier,
                'position' => $rule->side->value,
                // winning_numbers.payout_multiplier is unsignedInteger, exactly like
                // bet_items.payout_multiplier. toBetItemColumn() THROWS on a
                // fractional rate rather than truncating one, so a rate that cannot
                // be stored exactly aborts the publication instead of being rounded.
                'payout_multiplier' => $multiplier->toBetItemColumn(),
                'published_at' => now(),
                'metadata' => [
                    'market' => $marketKey,
                    'result_type' => $tier,
                    'match_mode' => $rule->matchMode(),
                    'digits' => $rule->digits(),
                    'multiplier_exact' => $multiplier->value(),
                    'multiplier_source' => $rule->multiplierSource(),
                    'source_value' => $rule->resultType()->storageDescription(),
                    'published_by_phase' => '5.1',
                ],
            ]);

            // total_winners and total_payout are deliberately NOT set. They are
            // settlement summaries and are excluded from $fillable anyway.
            $row->save();

            $rows[] = $row;
        }

        if ($rows === []) {
            throw DrawLifecycleException::duplicatePublication(
                (int) $draw->getKey(),
                'no configured market produced a winning number, so publishing would store an empty '
                .'official result',
                ['stage' => 'publication'],
            );
        }

        return $rows;
    }

    /**
     * The market rules a publication writes a winning number for.
     *
     * Enabled markets only, read from configuration. A disabled market gets no
     * official number, which is correct: nothing can have been sold on it.
     *
     * @return array<string, MarketRuleData>
     */
    private function publishableRules(): array
    {
        return array_filter(
            $this->rules->all(),
            static fn (MarketRuleData $rule): bool => $rule->enabled(),
        );
    }

    /**
     * The metadata key that carries the bottom two.
     */
    private function bottomTwoMetadataKey(): string
    {
        return $this->validator->bottomTwoMetadataKey();
    }

    /**
     * Whether a query failure is a unique constraint violation.
     *
     * Matched on the SQLSTATE class, which is 23000 for an integrity constraint
     * violation in both MariaDB and SQLite, so the check does not depend on a vendor
     * specific error number.
     */
    private function isUniqueViolation(QueryException $exception): bool
    {
        return $exception->getCode() === '23000' || $exception->getCode() === 23000;
    }
}
